/**
 * Compliance Footer - Legal disclaimers and compliance information
 * Includes AI disclaimer, privacy policy, terms of service, and regulatory notices
 */

import React from 'react';
import { trackEvent } from '../../lib/boards';

interface ComplianceFooterProps {
  className?: string;
}

const ComplianceFooter: React.FC<ComplianceFooterProps> = ({ className = '' }) => {
  const currentYear = new Date().getFullYear();

  const handleLinkClick = (linkType: string, url: string) => {
    trackEvent('footer_link_click', { 
      link_type: linkType,
      url: url 
    });
  };

  return (
    <footer className={`bg-ink-900 text-white py-12 ${className}`}>
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        {/* AI Disclaimer Banner */}
        <div className="bg-yellow-900/20 border border-yellow-700/30 rounded-lg p-6 mb-8">
          <div className="flex items-start gap-4">
            <div className="w-8 h-8 bg-yellow-500 rounded-lg flex items-center justify-center flex-shrink-0">
              <svg className="w-5 h-5 text-yellow-900" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
            </div>
            <div className="flex-1">
              <h3 className="text-lg font-semibold text-yellow-300 mb-2">
                🤖 AI-Generated Content Disclaimer
              </h3>
              <p className="text-yellow-100 leading-relaxed mb-4">
                <strong>AdvisorBoard uses artificial intelligence to simulate expert consultations.</strong> All advisor responses are generated by AI systems trained on domain knowledge and are not provided by real human experts.
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-yellow-200">
                <div>
                  <h4 className="font-medium mb-2">⚠️ Important Limitations:</h4>
                  <ul className="space-y-1 list-disc list-inside">
                    <li>AI responses are for educational and brainstorming purposes only</li>
                    <li>Not a substitute for professional medical, legal, or financial advice</li>
                    <li>May contain inaccuracies or outdated information</li>
                    <li>Should not be used for critical business or health decisions</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-medium mb-2">✅ Recommended Use:</h4>
                  <ul className="space-y-1 list-disc list-inside">
                    <li>Brainstorming and ideation sessions</li>
                    <li>Educational exploration of topics</li>
                    <li>Preliminary research and analysis</li>
                    <li>Team discussion facilitation</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Main Footer Content */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
          {/* Company Info */}
          <div>
            <h3 className="text-xl font-bold mb-4">AdvisorBoard</h3>
            <p className="text-ink-300 mb-4 leading-relaxed">
              AI-powered advisory consultations across specialized domains. 
              Harness collective intelligence for better decision-making.
            </p>
            <div className="flex items-center gap-4">
              <button
                onClick={() => handleLinkClick('social', 'twitter')}
                className="w-10 h-10 bg-ink-800 rounded-lg flex items-center justify-center hover:bg-ink-700 transition-colors duration-hover"
                aria-label="Follow us on Twitter"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/>
                </svg>
              </button>
              <button
                onClick={() => handleLinkClick('social', 'linkedin')}
                className="w-10 h-10 bg-ink-800 rounded-lg flex items-center justify-center hover:bg-ink-700 transition-colors duration-hover"
                aria-label="Connect on LinkedIn"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                </svg>
              </button>
            </div>
          </div>

          {/* Product Links */}
          <div>
            <h4 className="font-semibold mb-4">Product</h4>
            <ul className="space-y-3 text-ink-300">
              <li>
                <button
                  onClick={() => handleLinkClick('product', '/features')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Features
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('product', '/pricing')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Pricing
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('product', '/api')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  API Documentation
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('product', '/integrations')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Integrations
                </button>
              </li>
            </ul>
          </div>

          {/* Support Links */}
          <div>
            <h4 className="font-semibold mb-4">Support</h4>
            <ul className="space-y-3 text-ink-300">
              <li>
                <button
                  onClick={() => handleLinkClick('support', '/help')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Help Center
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('support', '/contact')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Contact Us
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('support', '/status')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  System Status
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('support', '/community')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Community
                </button>
              </li>
            </ul>
          </div>

          {/* Legal Links */}
          <div>
            <h4 className="font-semibold mb-4">Legal</h4>
            <ul className="space-y-3 text-ink-300">
              <li>
                <button
                  onClick={() => handleLinkClick('legal', '/privacy')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Privacy Policy
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('legal', '/terms')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Terms of Service
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('legal', '/cookies')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Cookie Policy
                </button>
              </li>
              <li>
                <button
                  onClick={() => handleLinkClick('legal', '/compliance')}
                  className="hover:text-white transition-colors duration-hover"
                >
                  Compliance
                </button>
              </li>
            </ul>
          </div>
        </div>

        {/* Regulatory Notices */}
        <div className="border-t border-ink-800 pt-8 mb-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm text-ink-400">
            <div>
              <h4 className="font-medium text-ink-300 mb-2">🏥 Medical Disclaimer</h4>
              <p>
                AdvisorBoard is not a medical device and does not provide medical advice. 
                Consult qualified healthcare professionals for medical decisions.
              </p>
            </div>
            <div>
              <h4 className="font-medium text-ink-300 mb-2">⚖️ Legal Disclaimer</h4>
              <p>
                AI-generated content does not constitute legal advice. 
                Consult licensed attorneys for legal matters and compliance requirements.
              </p>
            </div>
          </div>
        </div>

        {/* Copyright */}
        <div className="border-t border-ink-800 pt-8 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-ink-400 text-sm">
            © {currentYear} AdvisorBoard. All rights reserved.
          </p>
          <div className="flex items-center gap-6 text-sm text-ink-400">
            <span>🤖 Powered by AI</span>
            <span>🔒 SOC 2 Compliant</span>
            <span>🌍 Global Privacy Certified</span>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default ComplianceFooter;